const SESSION_BASE_PATH = process.env.SUBBOT_SESSIONS_PATH
  ? process.env.SUBBOT_SESSIONS_PATH
  : process.env.DOCKER_MODE === 'true'
    ? '/app/subbot-sessions'
    : './data/subbot-sessions';

export const SUBBOT_CONFIG = {
  MAX_SLOTS: 50,
  DEFAULT_SLOTS: 15,
  PAIRING_CODE_CACHE_MS: 60000,
  PUBLIC_REQUESTS: true,
  SLOT_STAGGER_MS: 700,
  SLOT_STAGGER_MAX_MS: 8000,
  SESSION_BASE_PATH,
  RUNTIME_STATE_DIR: './data/runtime/bot-states',
  BOT_RUNTIME_STATE_TTL_MS: 120000,
  RUNTIME_STATE_WRITE_DEBOUNCE_MS: 5000,
  MESSAGE_DEDUP_TTL_MS: 60000,
  MESSAGE_DEDUP_MAX_ENTRIES: 4000,
  CONTACT_CACHE_TTL_MS: 10 * 60 * 1000,
  CONTACT_CACHE_MAX_ENTRIES: 3000,
  PROFILE_APPLY_DELAY_MS: 15000,
  HEALTH_CHECK_INTERVAL: 2 * 60 * 1000,
  HEALTH_CHECK_CONFIRM_MS: 60 * 1000,
  BOT_CONNECTING_STALE_MS: 5 * 60 * 1000,
  BOT_PAIRING_STALE_MS: 5 * 60 * 1000,
  SETTINGS_SYNC_INTERVAL_MS: 60 * 1000,
} as const;

export const SUBBOT_COMMAND_TIMEOUT_MS = 3 * 60 * 1000;
export const SUBBOT_DOWNLOAD_TIMEOUT_MS = 12 * 60 * 1000;
