export const TIME = {
  SECOND: 1_000,
  MINUTE: 60 * 1_000,
  HOUR: 60 * 60 * 1_000,
  DAY: 24 * 60 * 60 * 1_000,
  WEEK: 7 * 24 * 60 * 60 * 1_000,
} as const;

export const RATE_LIMITS = {
  MAX_MESSAGES_PER_SECOND: 3,
  MAX_MESSAGES_PER_MINUTE: 20,
  ANTI_SPAM_BAN_DURATION: 5 * TIME.MINUTE,
  ANTI_SPAM_WARNING_INTERVAL: 60 * TIME.SECOND,
  ANTI_SPAM_MAX_AGE: 5 * TIME.MINUTE,
} as const;

export const CACHE = {
  DEFAULT_TTL: 5 * TIME.MINUTE,
  USER_TTL: 30 * TIME.MINUTE,
  GROUP_METADATA_TTL: 10 * TIME.MINUTE,
  PERMISSIONS_TTL: 3 * TIME.MINUTE,
  MESSAGE_DEDUP_CLEANUP: 5 * TIME.MINUTE,
} as const;

export const DOWNLOAD = {
  MAX_AUDIO_SIZE_MB: 50,
  MAX_VIDEO_SIZE_MB: 100,
  TIMEOUT: 90 * TIME.SECOND,
  YOUTUBE_TIMEOUT: 180 * TIME.SECOND,
  SOCIAL_TIMEOUT: 120 * TIME.SECOND,
} as const;

export const MEDIA = {
  STICKER_SIZE: 512,
  MAX_MEDIA_SIZE: 52428800,
  COMPRESSION_AUDIO_SIZE_MB: 25,
  MIN_AUDIO_SIZE_BYTES: 1000,
} as const;

export const DATABASE = {
  BATCH_INTERVAL: 3 * TIME.SECOND,
  MAX_BATCH_SIZE: 100,
  CACHE_MAX_SIZE: 10000,
  FORCE_SAVE_INTERVAL: 30 * TIME.SECOND,
  SAVE_DELAY: 2 * TIME.SECOND,
} as const;

export const AUTH = {
  MAX_QR_RETRIES: 10,
  MAX_RECONNECT_ATTEMPTS: 20,
  MAX_RECONNECT_DELAY: 5 * 60_000,
  FIRST_RECONNECT_DELAY: 15_000,
  RECONNECT_BASE_DELAY: 1_000,
  ERROR_515_MAX_RETRIES: 3,
  PAIRING_CODE_EXPIRY: 3 * TIME.MINUTE,
} as const;

export const MAX_RECONNECT_ATTEMPTS = 20;
export const MAX_RECONNECT_DELAY = 5 * 60_000;
export const FIRST_RECONNECT_DELAY = 15_000;
export const RECONNECT_BASE_DELAY = 1_000;

export const MAINTENANCE = {
  CLEANUP_INTERVAL: TIME.HOUR,
  USER_INACTIVITY_THRESHOLD: 7 * TIME.DAY,
  LISTA_TTL: 12 * TIME.HOUR,
} as const;

export const AI = {
  SESSION_TTL: 30 * TIME.MINUTE,
  CLEANUP_INTERVAL: 5 * TIME.MINUTE,
  PERSIST_INTERVAL: 2 * TIME.MINUTE,
  MAX_HISTORY_MESSAGES: 20,
  QUESTION_CACHE_TTL: 2 * TIME.HOUR,
} as const;
